name: Test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm i
      - run: npm run build
      - run: npm run test